name: CI Workflow
on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Setup frontend
        run: ./scripts/setup-frontend.sh
      - uses: pre-commit/action@v3.0.1
